version: '3.9'

services:
  db:    
    image: postgres:14.2
    container_name: atcs-db
    hostname: ${DB_HOST_NAME}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: atcs-db-admin
    depends_on:
      - db
    env_file:
      - .env
    ports:
     - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - backend

volumes:
  postgres-data:
  pgadmin-data:


networks:
  backend:
    driver: bridge